### ISSUE TITLE
Update to use policy deployment and update README

### ISSUE THREAD

**Issue by adhishreekadam** [open-horizon-services/web-helloworld-c#16]
Update to use policy deployment files and update README with full details:
    1. Front matter
    2. Shields - license should match LICENSE file
    3. Description
    4. Prerequisites
    5. Installation
    6. Usage
    7. Advanced Details
    8. Authors - should match MAINTAINERS.md

**Comment by adhishreekadam** [comment]
@joewxboy can you please assign this to me

**Comment by joewxboy** [comment]
> @joewxboy can you please assign this to me

Done!  Enjoy. :)
