### ISSUE TITLE
Add Makefile targets and horizon files

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-c#2]
Eventually we will want to add the following Makefile targets 
```
publish-service:

publish-pattern:

register-pattern:
```

in addition to the corresponding `service.json` and `pattern.json` files

**Comment by julianchen215** [comment]
Hi @t-fine and @joewxboy, can you please assign this issue to me?

**Comment by joewxboy** [comment]
You got it, @julianchen215

**Comment by johnwalicki** [comment]
@julianchen215  Nice work!  Closing issue.
