### ISSUE TITLE
Modify Makefile to allow DOCKER_HUB_ID to be overridden by env var

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-c#3]
In the future we plan to have a more advanced CI/CD process and allowing the `DOCKER_HUB_ID` to be overridden by an environment variable will needed. 

We should change 
``` 
DOCKERHUB_ID:=ibmosquito
``` 
to the following
```
DOCKER_HUB_ID ?= ibmosquito
```

**Comment by oskurtt** [comment]
Can i get assigned to this?

**Comment by joewxboy** [comment]
Sure, @oskurtt 

Make sure that you find all instances of `DOCKERHUB_ID` in the file and change them to `DOCKER_HUB_ID` in addition to the initial change that Troy mentioned.  Make sure you sign off on all of your commits.
